### ISSUE TITLE
Add WCA ID to API

### ISSUE THREAD

**Issue by LinusFresz** [ciscou/cubecomps-mobile#7]
It would be really nice to have the WCA IDs in most of the APIs: 
* Results for a round
* Results for a competitor
* Competitors of a competition

As the WCA ID somehow must be saved by cubecomps anyway, it would be awesome to also add it to the API!

Example usage:
https://www.cubecomps.com/live.php?cid=4491&cat=2&rnd=1
Last weekend we had two competitors with an identical name (Anatoly Turenko) at German Nationals 2019. To match their cubecomps information with the WCA website, currently one can only use the name which caused missmatches (the registration id might differ between cubecomps and WCA registration), therefore a WCA ID would at least solve this problem for competitors with WCA ID!

**Comment by ciscou** [comment]
Sorry, for some reason I missed this issue.

I was talking to Jeremy Fleischman one week ago and I needed exactly this (in order to add a link to the WCA page to see the official schedule of a competition).

Sadly, cubecomps (the real one, the desktop version) does not even save the WCA ID of the competitions anywhere at all. So the only way of doing this is keeping a manually crafted table of correspondences between cubecomps ids and wca ids, which we're not ready to do as of now :(

If we think of an alternative, I'll let you know

Thanks for your interesest, and sorry but there's nothing we can do :(

(Re-reading your issue, I think you were talking about competitor ids and I was talking about competition ids, but the same applies: it's nowhere in the HTML that I can scrap, it's not even stored in the database, so there is nothing I can do)

**Comment by LinusFresz** [comment]
Thank you for your reply! You are sure speaking about the competition ID while I am talking about WCA IDs (IDs for each competitor), so there is some difference between those. :) And I would also differentiate between competitor IDs and WCA IDs, because cubecomps assigns competitor IDs (numbers, given by the order in which the competitors have been imported) and WCA IDs (for competitors who already went to a competition before).

I am a bit confused about this btw, because cubecomps does include the WCA IDs in the export and displays them in the admin view of all competitors for each competition, so it sure must be saved somewhere in cubecomps?
Also the results of indivdual competitors link to their WCA profiles (given they have a WCA ID), so I assume they should be stored in the database.

**Comment by ciscou** [comment]
I'm so sorry I missed the notifications again... that should just not happen :(

You're right, the WCA id of the competitor is there in the HTML and I could add that to the API (only to the list of results of that competitor, because that's the only endpoint where I scrape a HTML which happens to have that info in it)

Do you still need that? What endpoint of the API are you using? https://m.cubecomps.com/competitions/4620/competitors/63.json, https://m.cubecomps.com/api/v1/competitions/4620/competitors/63.json or https://m.cubecomps.com/api/v2/competitions/4620/competitors/63.json ?

**Comment by LinusFresz** [comment]
That would be awesome! :) 

Currently I am using https://m.cubecomps.com/api/v1/competitions/4620 and https://m.cubecomps.com/api/v1/competitions/4620/events/1/rounds/1 for
a) collecting competitor information (more specific: registration ID of each competitor) and
b) finding proceeding competitors for consecutive rounds to print scoresheets for second/third/fourth rounds.
For both I need to do a match between WCA registration and information on cubecomps which I do by name comparison, but could be 100% correct if I could do it with WCA IDs.

**Comment by ciscou** [comment]
OK I'll merge the PR I linked above when Sunday is over (in case I break something, I don't want that to happen while there are competitions in progress).

You'll have to do a request to https://m.cubecomps.com/api/v1/competitions/4620/competitors/63.json to fetch the wca_id of a competitor (because, as I said, that's the only endpoint where I scrape a page in desktop cubecomps that has the wca id in the HTML :()

Hope that's OK for you :)

I'll let you know when the PR is merged and the `wca_id` field is available.

**Comment by ciscou** [comment]
https://github.com/ciscou/cubecomps-mobile/pull/8 has been merged.

https://m.cubecomps.com/api/v1/competitions/4620/competitors/63.json (notice the new root-level field `wca_id`)

Also, have into account that not all competitors have a wca_id (because it's their first competition or just because they forgot to enter their ID when they registered). In that case, `wca_id` is empty (`""`). Example: https://m.cubecomps.com/api/v1/competitions/4620/competitors/69.json
